package com.myhaimi.sms.entity.enums;

public enum FileCategory {
    PROFILE_PHOTO,
    STUDENT_DOCUMENT,
    GUARDIAN_DOCUMENT,
    TEACHER_DOCUMENT,
    ASSIGNMENT_ATTACHMENT,
    ASSIGNMENT_SUBMISSION,
    LECTURE_NOTE,
    CIRCULAR_ATTACHMENT,
    PAYROLL_SLIP,
    FEE_RECEIPT,
    REPORT_CARD,
    TRANSFER_CERTIFICATE,
    GENERAL
}

